import type { Meta, StoryObj } from '@storybook/react-vite';
import { GanttPro } from '../components/Gantt/GanttPro';
import type { Task, Link, Baseline } from '../components/types';
import '../components/Gantt/gantt.css';

const meta = {
  title: 'SVAR PRO/Gantt Pro Features',
  component: GanttPro,
  parameters: {
    layout: 'fullscreen',
  },
  tags: ['autodocs'],
} satisfies Meta<typeof GanttPro>;

export default meta;
type Story = StoryObj<typeof meta>;

// Comprehensive project with all data
const comprehensiveProject: Task[] = [
  {
    id: '1',
    text: 'Q1 Planning',
    start: new Date(2024, 0, 1),
    end: new Date(2024, 0, 15),
    duration: 14,
    progress: 100,
    type: 'project',
    open: true,
    color: '#52C785',
    owner: 'Sarah Johnson',
    priority: 'high',
  },
  {
    id: '1.1',
    text: 'Market Analysis',
    start: new Date(2024, 0, 1),
    end: new Date(2024, 0, 8),
    duration: 7,
    progress: 100,
    parent: '1',
    color: '#4A90E2',
    owner: 'John Smith',
    priority: 'high',
    details: 'Comprehensive market research and competitor analysis',
  },
  {
    id: '1.2',
    text: 'Strategy Workshop',
    start: new Date(2024, 0, 8),
    end: new Date(2024, 0, 15),
    duration: 7,
    progress: 100,
    parent: '1',
    color: '#4A90E2',
    owner: 'Sarah Johnson',
    priority: 'high',
    details: 'Team workshop to define strategy',
  },
  {
    id: '2',
    text: 'Product Development',
    start: new Date(2024, 0, 15),
    end: new Date(2024, 2, 30),
    duration: 75,
    progress: 60,
    type: 'project',
    open: true,
    color: '#52C785',
    owner: 'Mike Chen',
    priority: 'high',
  },
  {
    id: '2.1',
    text: 'UI/UX Design',
    start: new Date(2024, 0, 15),
    end: new Date(2024, 1, 5),
    duration: 21,
    progress: 100,
    parent: '2',
    color: '#9B59B6',
    owner: 'Emily Davis',
    priority: 'high',
    details: 'Complete UI/UX design for all screens',
  },
  {
    id: '2.2',
    text: 'Frontend Development',
    start: new Date(2024, 1, 5),
    end: new Date(2024, 2, 5),
    duration: 29,
    progress: 75,
    parent: '2',
    color: '#E74C3C',
    owner: 'Alex Rodriguez',
    priority: 'high',
    details: 'React component development',
  },
  {
    id: '2.3',
    text: 'Backend API',
    start: new Date(2024, 1, 12),
    end: new Date(2024, 2, 15),
    duration: 32,
    progress: 65,
    parent: '2',
    color: '#E74C3C',
    owner: 'Mike Chen',
    priority: 'high',
    details: 'REST API development with Node.js',
  },
  {
    id: '2.4',
    text: 'Database Setup',
    start: new Date(2024, 1, 15),
    end: new Date(2024, 1, 25),
    duration: 10,
    progress: 90,
    parent: '2',
    color: '#E74C3C',
    owner: 'David Kim',
    priority: 'medium',
    details: 'PostgreSQL database schema and migrations',
  },
  {
    id: '2.5',
    text: 'Integration Testing',
    start: new Date(2024, 2, 15),
    end: new Date(2024, 2, 30),
    duration: 15,
    progress: 30,
    parent: '2',
    color: '#F39C12',
    owner: 'Lisa Wang',
    priority: 'high',
    details: 'End-to-end integration testing',
  },
  {
    id: '3',
    text: 'QA & Testing',
    start: new Date(2024, 2, 30),
    end: new Date(2024, 3, 20),
    duration: 21,
    progress: 20,
    type: 'project',
    open: true,
    color: '#52C785',
    owner: 'Lisa Wang',
    priority: 'high',
  },
  {
    id: '3.1',
    text: 'Unit Testing',
    start: new Date(2024, 2, 30),
    end: new Date(2024, 3, 8),
    duration: 9,
    progress: 40,
    parent: '3',
    color: '#F39C12',
    owner: 'Lisa Wang',
    priority: 'high',
    details: 'Comprehensive unit test coverage',
  },
  {
    id: '3.2',
    text: 'User Acceptance Testing',
    start: new Date(2024, 3, 8),
    end: new Date(2024, 3, 20),
    duration: 12,
    progress: 10,
    parent: '3',
    color: '#F39C12',
    owner: 'Sarah Johnson',
    priority: 'high',
    details: 'UAT with stakeholders',
  },
  {
    id: '4',
    text: 'Deployment',
    start: new Date(2024, 3, 20),
    end: new Date(2024, 3, 30),
    duration: 10,
    progress: 0,
    type: 'project',
    open: true,
    color: '#52C785',
    owner: 'Mike Chen',
    priority: 'high',
  },
  {
    id: '4.1',
    text: 'Staging Deployment',
    start: new Date(2024, 3, 20),
    end: new Date(2024, 3, 25),
    duration: 5,
    progress: 0,
    parent: '4',
    color: '#3498DB',
    owner: 'David Kim',
    priority: 'high',
    details: 'Deploy to staging environment',
  },
  {
    id: '4.2',
    text: 'Production Launch',
    start: new Date(2024, 3, 25),
    end: new Date(2024, 3, 30),
    duration: 5,
    progress: 0,
    parent: '4',
    color: '#3498DB',
    owner: 'Mike Chen',
    priority: 'high',
    details: 'Production deployment and monitoring',
  },
  // Milestones
  {
    id: 'm1',
    text: 'Project Kickoff',
    start: new Date(2024, 0, 1),
    end: new Date(2024, 0, 1),
    duration: 0,
    progress: 100,
    type: 'milestone',
    color: '#2196F3',
    priority: 'high',
  },
  {
    id: 'm2',
    text: 'Design Complete',
    start: new Date(2024, 1, 5),
    end: new Date(2024, 1, 5),
    duration: 0,
    progress: 100,
    type: 'milestone',
    color: '#2196F3',
    priority: 'high',
  },
  {
    id: 'm3',
    text: 'Development Complete',
    start: new Date(2024, 2, 30),
    end: new Date(2024, 2, 30),
    duration: 0,
    progress: 0,
    type: 'milestone',
    color: '#2196F3',
    priority: 'high',
  },
  {
    id: 'm4',
    text: 'Go Live',
    start: new Date(2024, 3, 30),
    end: new Date(2024, 3, 30),
    duration: 0,
    progress: 0,
    type: 'milestone',
    color: '#2196F3',
    priority: 'high',
  },
];

const comprehensiveLinks: Link[] = [
  { id: 'l1', source: '1.1', target: '1.2', type: 'e2s' },
  { id: 'l2', source: '1.2', target: '2.1', type: 'e2s' },
  { id: 'l3', source: '2.1', target: '2.2', type: 'e2s' },
  { id: 'l4', source: '2.1', target: '2.3', type: 'e2s' },
  { id: 'l5', source: '2.3', target: '2.4', type: 's2s' },
  { id: 'l6', source: '2.2', target: '2.5', type: 'e2s' },
  { id: 'l7', source: '2.3', target: '2.5', type: 'e2s' },
  { id: 'l8', source: '2.5', target: '3.1', type: 'e2s' },
  { id: 'l9', source: '3.1', target: '3.2', type: 'e2s' },
  { id: 'l10', source: '3.2', target: '4.1', type: 'e2s' },
  { id: 'l11', source: '4.1', target: '4.2', type: 'e2s' },
];

// Full PRO features demo
export const AllProFeatures: Story = {
  args: {
    tasks: comprehensiveProject,
    links: comprehensiveLinks,
    config: {
      weekends: true,
      theme: 'light',
      readonly: false,
      editable: true,
      autoSchedule: true,
      criticalPath: true,
      baselines: true,
    },
  },
};

// Dark theme with all features
export const DarkThemeProFeatures: Story = {
  args: {
    ...AllProFeatures.args,
    config: {
      ...AllProFeatures.args?.config,
      theme: 'dark',
    },
  },
};

// Focus on filtering and search
const diverseTasks: Task[] = [
  {
    id: 't1',
    text: 'High Priority Backend Task',
    start: new Date(2024, 2, 1),
    end: new Date(2024, 2, 10),
    duration: 9,
    progress: 80,
    color: '#E74C3C',
    owner: 'Mike Chen',
    priority: 'high',
  },
  {
    id: 't2',
    text: 'Medium Priority Frontend Task',
    start: new Date(2024, 2, 5),
    end: new Date(2024, 2, 15),
    duration: 10,
    progress: 50,
    color: '#3498DB',
    owner: 'Alex Rodriguez',
    priority: 'medium',
  },
  {
    id: 't3',
    text: 'Low Priority Documentation',
    start: new Date(2024, 2, 10),
    end: new Date(2024, 2, 20),
    duration: 10,
    progress: 30,
    color: '#95A5A6',
    owner: 'Sarah Johnson',
    priority: 'low',
  },
  {
    id: 't4',
    text: 'Completed Database Setup',
    start: new Date(2024, 2, 1),
    end: new Date(2024, 2, 5),
    duration: 4,
    progress: 100,
    color: '#27AE60',
    owner: 'David Kim',
    priority: 'high',
  },
  {
    id: 't5',
    text: 'Not Started API Development',
    start: new Date(2024, 2, 20),
    end: new Date(2024, 2, 30),
    duration: 10,
    progress: 0,
    color: '#F39C12',
    owner: 'Mike Chen',
    priority: 'medium',
  },
];

export const FilteringAndSearch: Story = {
  args: {
    tasks: diverseTasks,
    links: [],
    config: {
      weekends: true,
      theme: 'light',
    },
  },
};

// Resource leveling demo
const overlappingTasks: Task[] = [
  {
    id: 'r1',
    text: 'Task 1 for John',
    start: new Date(2024, 2, 1),
    end: new Date(2024, 2, 10),
    duration: 9,
    progress: 50,
    owner: 'John Smith',
    color: '#3498DB',
    priority: 'high',
  },
  {
    id: 'r2',
    text: 'Task 2 for John (overlaps)',
    start: new Date(2024, 2, 5),
    end: new Date(2024, 2, 15),
    duration: 10,
    progress: 30,
    owner: 'John Smith',
    color: '#E74C3C',
    priority: 'medium',
  },
  {
    id: 'r3',
    text: 'Task 3 for John (overlaps)',
    start: new Date(2024, 2, 8),
    end: new Date(2024, 2, 18),
    duration: 10,
    progress: 20,
    owner: 'John Smith',
    color: '#F39C12',
    priority: 'low',
  },
  {
    id: 'r4',
    text: 'Task for Sarah',
    start: new Date(2024, 2, 1),
    end: new Date(2024, 2, 12),
    duration: 11,
    progress: 60,
    owner: 'Sarah Johnson',
    color: '#9B59B6',
    priority: 'high',
  },
];

export const ResourceLeveling: Story = {
  args: {
    tasks: overlappingTasks,
    links: [],
    config: {
      weekends: true,
      theme: 'light',
    },
  },
};

// Undo/Redo demo
export const UndoRedoDemo: Story = {
  args: {
    tasks: [
      {
        id: 'u1',
        text: 'Task 1',
        start: new Date(2024, 2, 1),
        end: new Date(2024, 2, 5),
        duration: 4,
        progress: 50,
        color: '#3498DB',
        priority: 'medium',
      },
      {
        id: 'u2',
        text: 'Task 2',
        start: new Date(2024, 2, 5),
        end: new Date(2024, 2, 10),
        duration: 5,
        progress: 30,
        color: '#E74C3C',
        priority: 'high',
      },
    ],
    links: [{ id: 'lu1', source: 'u1', target: 'u2', type: 'e2s' }],
    config: {
      weekends: true,
      theme: 'light',
    },
  },
};
